### ISSUE TITLE
Sqrt function

### ISSUE THREAD

**Issue by cmj91uk** [less/less-docs#310] opened 2015-03-05 20:15 UTC
In the documentation for the mathematical functions the sqrt documentation indicates that the sqrt(18.6%) returns 4.31% which is incorrect. 

sqrt(18.6%) = 43.1% rather than 4.31.
sqrt(18.6) is 4.31 but 4.31% * 4.31% = 0.18%

**Comment by seven-phases-max** [comment] 2015-03-06 00:10
Well, no. In Less, units do not have any special meaning for arithmetic operations. Thus `1% * 1%` does not mean "`1%` *of* `1%`" but just `1 * 1` with the result inheriting the unit of the first operand (handling different units depending on the [`--strict-units` option](http://lesscss.org/usage/#command-line-usage-strict-units)). 
For more details see https://github.com/less/less.js/issues/1366.

**Comment by seven-phases-max** [comment] 2015-03-06 00:10
Closing as "intended behaviour".

**Closed by seven-phases-max** 2015-03-06 00:10 UTC
