### ISSUE TITLE
lesscss can't parse case-insensitive attribute selector

### ISSUE THREAD

**Issue by ccoenen** [less/less-docs#467] opened 2018-02-28 22:32 UTC
I have attributes selected like this:
`.entry[data-title="active" i] {color: red}`

less (3.0.1) will complain:

```
    Expected ']' got 'i'
          in ....filename.... (line 3, column 64)
```

But the "i" (or "I") is according to spec, see [MDN on Attribute Selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), and is [widely supported](https://caniuse.com/#feat=css-case-insensitive)

I would also be satisfied with something like an uprocessed region or something like that.

**Comment by seven-phases-max** [comment] 2018-03-01 11:07
Note this is the issue tracker of the Less documentation. For Less language and compiler bugs/uses use https://github.com/less/less.js/issues.

The quick answer would be: use either [`(inline)`](http://lesscss.org/features/#import-atrules-feature-import-options) (= "unprocessed file") or move the exotic value to a variable ([escape](http://lesscss.org/#escaping) if necessary): [Example](http://lesscss.org/less-preview/#%7B%22less%22%3A%22%40cia%3A%20%5C%22active%5C%22%20i%3B%5Cn.entry%5Bdata-title%3D%40%7Bcia%7D%5D%20%7B%5Cn%20%20%20%20color%3A%20red%5Cn%7D%22%7D).

**Comment by seven-phases-max** [comment] 2018-03-01 11:09
Closing as "wrong-repo" (and duplicate of https://github.com/less/less.js/issues/3027).

**Closed by seven-phases-max** 2018-03-01 11:09 UTC

**Comment by ccoenen** [comment] 2018-03-01 12:11
whoops! Thanks for pointing out the right issue :-)
