### ISSUE TITLE
Mixin Issue!

### ISSUE THREAD

**Issue by mastermehdi** [less/less-docs#435] opened 2017-02-08 06:39 UTC
Hi
At the moment when we write this in less
`.test() {
    color: white;
}
.test() {
    color: red;
}
body {
    .test()
}`

Compiled to:
`a {
  color: white;
  color: red;
}`

But desired compile is:
`a {
  color: red;
}`

**Comment by matthew-dean** [comment] 2017-02-08 06:46
This is expected behavior. Properties cannot be reduced because different values may be valid in different browsers. As in:

```
a {
  display: grid;
  display: inline-block;
}
```
(Also wrong repo.)

**Comment by matthew-dean** [comment] 2017-02-08 06:46
Closing as expected behavior.

**Closed by matthew-dean** 2017-02-08 06:46 UTC

**Comment by mastermehdi** [comment] 2017-02-10 13:55
Can we add a new feature to mixin for supporting both of them?

**Comment by seven-phases-max** [comment] 2017-02-10 15:11
@mastermehdi

This is a reposetory for the Less documentation. For Less language issue reports and feature requeststs use https://github.com/less/less.js/issues. Before ctreating a new ticket please review https://github.com/less/less.js/blob/3.x/CONTRIBUTING.md.
