### ISSUE TITLE
"Frameworks Using Less" Needs Urgent Updating

### ISSUE THREAD

**Issue by luxlogica** [less/less-docs#442] opened 2017-04-21 00:36 UTC
The ["Frameworks Using Less"](http://lesscss.org/3.x/tools/#frameworks-using-less) section of the new docs is terribly out of date: many of the items listed are no longer maintained, while several others are no longer developed with Less:

- **ipxdeep** has not been updated since May 2015
- **Bootflat** was last updated a year ago (dead?)
- **Bootstrap** version 4 is developed in Sass
- **Bootstrap a11y theme** was last updated in February 2014
- **Cardinal** was last updated a year ago (dead?)
- **CSSHórus** was last updated in January 2014
- **Frontsize** is now developed in Sass
- **InContent** is not a framework, the URL linking to it is wrong, and it hasn't been updated since 2014
- **Ink** is now developed in Sass
- **JBST** was last updated in August 2014
- **KNACSS** is now developed in Sass
- **Kube** is now developed in Sass
- **Pre** has not been updated since January 2013
- **Prelude** has not been updated since July 2014
- **ngBoilerplate** was last updated in January 2015

Projects which have given up on Less, or that are possibly abandoned or dead, should be removed from the list. These are no longer useful examples of Less being used or implemented, and having a shorter list - with projects that are very much alive and robust - is more efficient, and more encouraging. 

From the current list, the projects that seem to still be active are:

- [Ant Design](https://ant.design)
- [Metro UI](https://metroui.org.ua)
- [Schema](http://danmalarkey.github.io/schema/)
- **[Semantic UI](https://semantic-ui.com)**
- **[UIKit](https://getuikit.com)**
- [less-rails](https://github.com/metaskills/less-rails)
- [Wee](https://www.weepower.com)

IMHO, special emphasis should be given to both **Semantic UI** and **UIKit**, as these have become widely-known projects, with large online communities, which rival the better-known Sass frameworks.

**Comment by seven-phases-max** [comment] 2017-04-21 07:47
Not updated does not automatically mean dead and/or not useful anymore. (Personal example - [less-plugin-functions`](https://github.com/seven-phases-max/less-plugin-functions) has not been updated for *2 years* as well. Is it dead? No - it's just nothing to update, it works just fine with the latests Less versions and the only update I plan eventually is to *remove* some feature :)

Sure, some clean-up of this list is needed continuously but it's never really urgent (Especially since in many cases the flow is opposite - first you find a framework you need and only then you discover what's behind, so it's aways been more like a "honor list" rather then "what to use" one). 

**Either way** if you make a PR I'm pretty sure it's merged (assuming it won't be too harsh - e.g. Bootstrap 3 is still available and some people still use Bootstrap 2 for various reasons). So just a remark on emphasis - the problem is that it is always subjective and offensive, hence the alphabetic order being used in the first place.
<sub>A less popular thing *even if you have a statistic* is not necessary less useful, and popularity and rivalry are often not the primarily goals of many open-source projects. Fairness in opposite to Aggressive Advertising may sound harmful and weird from a commercial point of view, but Less is not the one and what it really needs now is more active developers - *not* more users (and unfortunately increasing the latter does not mean automatically increases the former)).</sub>

**Comment by seven-phases-max** [comment] 2017-04-23 22:40
Done with https://github.com/less/less-docs/commit/5624a6105a854edf45f494fda0b110d1d9cf42b8 (relaxed). Thanks!

**Closed by seven-phases-max** 2017-04-23 22:40 UTC

**Comment by matthew-dean** [comment] 2017-04-25 22:18
@seven-phases-max Thanks so much for your updates lately!
