### ISSUE TITLE
Remove -x deprecated compress option from the command-line examples

### ISSUE THREAD

**Issue by vinischeidegger** [less/less-docs#444] opened 2017-04-29 09:23 UTC
Although deprecated functions should be in the documentation, they shouldn't serve as examples, if the intent is not using them anymore.

**Comment by seven-phases-max** [comment] 2017-04-29 09:25
See #349.

**Comment by seven-phases-max** [comment] 2017-04-29 09:25
Closing as duplicate of #349.

**Comment by arndissler** [comment] 2018-03-29 13:46
Shouldn't this be closed?

**Comment by seven-phases-max** [comment] 2018-03-29 17:48
@arndissler Indeed. Thanks!

**Comment by seven-phases-max** [comment] 2018-03-29 17:49
Finally closing as implemented (`-x` examples are kicked from the docs already).

**Closed by seven-phases-max** 2018-03-29 17:49 UTC
