### ISSUE TITLE
XMLHttpRequest Deprecation..

### ISSUE THREAD

**Issue by Cordux** [less/less-docs#482] opened 2018-06-12 11:54 UTC
I have looked over the code for less.min.js and it needs to change for it.
Otherwise you get the error: 

> [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Correct way should be: 

> var xhr = new XMLHttpRequest()
> xhr.onreadystatechange = function() {
>     if (this.readyState === this.DONE) {
>         console.log(this.status) // do something; the request has completed
>     }
> }
> xhr.open("HEAD", "http://example.com") // replace with URL of your choosing
> xhr.send()

**Comment by seven-phases-max** [comment] 2018-06-12 13:05
1. Wrong repo (this is the repository for Less documentation, for Less compiler use https://github.com/less/less.js/).
2. See https://github.com/less/less.js/issues/2384.

**Comment by seven-phases-max** [comment] 2018-06-15 11:09
Closing as "wrong repo" (and duplicate of https://github.com/less/less.js/issues/2384).

**Closed by seven-phases-max** 2018-06-15 11:09 UTC
