### ISSUE TITLE
Extend的问题

### ISSUE THREAD

**Issue by yuyu19880526** [less/less-docs#356] opened 2015-08-21 08:19 UTC
在看Extend语言特性里，发现Extend
link:hover:visited {
  color: blue;
}
.selector:extend(link:visited:hover) {}
Outputs：
extend ' link:visited:hover' has no matches

:nth-child(1n+3) {
  color: blue;
}
.child:extend(n+3) {}
Outputs：
extend ' n + 3' has no matches
与官网的输出结果不一样

**Comment by matthew-dean** [comment] 2015-08-21 18:16
That's correct. 'link:visited:hover' has no matches. It's written as 'link:hover:visited'.  n+3 has no matches because it's not a selector.

Closing as expected behavior.

**Closed by matthew-dean** 2015-08-21 18:16 UTC
