### ISSUE TITLE
Bug with Parsing `calc` clauses

### ISSUE THREAD

**Issue by boris-marinov** [less/less-docs#441] opened 2017-04-04 12:19 UTC
The code:
```
        .rounds-inner {
            display: block;
            .matches-round {
                margin-left: calc(25% - 150px);
                margin-right: calc(25% - 150px);
            }
        }

```
Gets transferred as:

```
.usq-draws .rounds-container.mobile .rounds-inner {
  display: block;
}
.usq-draws .rounds-container.mobile .rounds-inner .matches-round {
  margin-left: calc(-125%);
  margin-right: calc(-125%);
}
```

**Comment by 4rChon** [comment] 2017-04-04 12:24
Check this out: http://stackoverflow.com/questions/11972084/less-aggressive-compilation-with-css3-calc

It seems to be a common problem with calc() and Less. It requries you to escape the values like so to get around this:

`calc(~"25% - 150px")`

**Comment by boris-marinov** [comment] 2017-04-04 12:27
Thanks, saw it. Still this is a bug, so leaving this opened.

**Comment by boris-marinov** [comment] 2017-04-04 12:37
I now see that this is documented behaviour, so it will probably be closed. Still, ` (25% - 150px) = -125%` makes zero sense.

**Comment by seven-phases-max** [comment] 2017-04-04 13:07
See http://lesscss.org/usage/#command-line-usage-strict-math.

**Comment by seven-phases-max** [comment] 2017-04-04 13:09
Closing as wrong repo (this repo is for the Less documentation, for Less language/compiler issues use https://github.com/less/less.js ... using search before!). And (currently) expected behaviour anyway.

**Closed by seven-phases-max** 2017-04-04 13:09 UTC

**Comment by matthew-dean** [comment] 2017-04-04 17:36
@boris-marinov You may also want to read through: https://github.com/less/less.js/issues/1880

**Comment by boris-marinov** [comment] 2017-04-05 09:15
I prefer not to. The value of `25%` is determined at runtime, so the calculation `(25% - 150px)` should also be left to be calculated there. In my opinion, you don't need a setting that performs it otherwise. And if you do got one, it surely does not make any sense for it to be the default.

**Comment by seven-phases-max** [comment] 2017-04-05 09:38
@boris-marinov "not to" what? (Did you actually read #1880? Please do). Realize that Less evaluates arithmetic expression anywhere, not just in `calc` (`(25% - 150px)` w/o `calc` is not even a CSS code), and the behaviour where Less is also preforming this for `calc` (while it should not) is only a result of CSS `calc` came in *after* Less is developed. So in short: eventually it won't, but this improvement does not have the highest priority, since the workaround is simple and well-known.

**Comment by boris-marinov** [comment] 2017-04-05 16:36
I really don't want to argue but in your website you say: 

>Less is a CSS pre-processor, meaning that it extends the CSS language.

For me, this implies that any valid CSS can pass through LESS without getting broken, which makes this a bug, and not an improvement. 

In general, when you use the word *workaround* there usually is a bug, or a *problem*, as you called it in the Google search you gave link to.

**Comment by seven-phases-max** [comment] 2017-04-05 18:50
>this implies that any valid CSS can pass through LESS without getting broken

No, it does not. That's not what's written there. No one ever in this galaxy or in this universe completely can promise 100% compatibility for *anything* at all (especially for things that change in time, where what's 100%-compatible today may become 100%-broken tomorrow). This would especially ridiculous for a thing like CSS with all of its infinite standards, drafts, browser-specific extensions and etc.

>In general, when you use the word workaround there usually is a bug involved

Just set [the mentioned option](https://github.com/less/less-docs/issues/441#issuecomment-291493684) and forget about it. The mentioned option just can't be set by default because it will immediately break every second Less project out there ("backward-compatibility, ding-dong). You've also been pointed to the open feature proposal ticket where an improvement to this behaviour is discussed (among the other related things). So, sorry, I just can't get what you're complaining about.
